title: azat.sh | presentations
description: "List of my presentations"
google_analytics: G-B0QQGN4BYM
show_downloads: false
# Use the latest version of the theme via jekyll-remote-theme, this is required
# for GA4 [1] that had been fixed in [2], but there was no release with this
# patch included.
#
#   [1]: https://github.com/jekyll/minima/issues/561
#   [1]: https://github.com/jekyll/minima/pull/281
remote_theme: jekyll/minima

gems:
  - jekyll-remote-theme
  - jekyll-mentions
