---
version: '2.2'

services:
  clickhouse-server:
    # 21.9 does not includes connection_wait_timeout for MySQL [1].
    #
    #   [1]: https://github.com/ClickHouse/ClickHouse/pull/28474
    #
    image: clickhouse/clickhouse-server:21.9
    expose:
      - 9000
      - 8123
    environment:
      - CLICKHOUSE_WATCHDOG_ENABLE=0
    depends_on:
      - mysql

  clickhouse-client:
    image: clickhouse/clickhouse-server:21.9
    depends_on:
      - clickhouse-server
    volumes:
      - $PWD/env:/env
    environment:
      - CLICKHOUSE_HISTORY_FILE=/env/.clickhouse-client-history
    command: clickhouse-client --host clickhouse-server

  mysql:
    # Prefered percona **8** since it has SEQUENCE_TABLE()
    image: percona:8
    environment:
      MYSQL_ROOT_PASSWORD: clickhouse
    expose:
      - 3306

networks:
  default:
    driver: bridge
    internal: true
    enable_ipv6: false
